export const English = [
  {
    text: "英语",
    collapsed: true,
    items: [
      { text: "总览", link: "/docs/English/总览" },
      { text: "常见发音对照表", link: "/docs/English/常见发音对照表" },
      { text: "主语", link: "/docs/English/主语" },
      { text: "谓语", link: "/docs/English/谓语" },
      { text: "表语", link: "/docs/English/表语" },
      { text: "宾语", link: "/docs/English/宾语" },
      { text: "状语", link: "/docs/English/状语" },
      { text: "定语", link: "/docs/English/定语" },
      { text: "同位语", link: "/docs/English/同位语" },
      { text: "基本句型", link: "/docs/English/基本句型" },
      { text: "名词与分类", link: "/docs/English/名词与分类" },
      { text: "名词单数变复数规则", link: "/docs/English/名词单数变复数规则" },
      { text: "不可数名词与量词", link: "/docs/English/不可数名词与量词" },
      { text: "名词的作用", link: "/docs/English/名词的作用" },
      { text: "名词所有格", link: "/docs/English/名词所有格" },
      { text: "人称代词", link: "/docs/English/人称代词" },
      { text: "物主代词", link: "/docs/English/物主代词" },
      { text: "指示代词", link: "/docs/English/指示代词" },
      { text: "形容词定义和语法", link: "/docs/English/形容词定义和语法" },
      { text: "形容词的比较级和最高级规则", link: "/docs/English/形容词的比较级和最高级规则" },
      { text: "形容词的比较级和最高级用法", link: "/docs/English/形容词的比较级和最高级用法" },
      { text: "谓语动词", link: "/docs/English/谓语动词" },
      { text: "实义动词格式变化", link: "/docs/English/实义动词格式变化" },
      { text: "系动词", link: "/docs/English/系动词" },
      { text: "助动词", link: "/docs/English/助动词" },
      { text: "情态动词", link: "/docs/English/情态动词" },
      { text: "冠词", link: "/docs/English/冠词" },
      { text: "一般现在时", link: "/docs/English/一般现在时" },
      { text: "主系表疑问句和否定句", link: "/docs/English/主系表疑问句和否定句" },
      { text: "主谓宾构成方式", link: "/docs/English/主谓宾构成方式" },
      { text: "主谓宾疑问句否定句", link: "/docs/English/主谓宾疑问句否定句" },
      { text: "16种时态", link: "/docs/English/16种时态" },

      { text: "序数词与基数词", link: "/docs/English/序数词与基数词" },

      { text: "否定句", link: "/docs/English/否定句" },
      { text: "肯定句转疑问句", link: "/docs/English/肯定句转疑问句" },
      { text: "特殊疑问句", link: "/docs/English/特殊疑问句" },
    ]
  }
]