export const dictTree = [
  {
    label: "中国考试",
    children: [
      {
        label: "大学英语",
        children: [
          {
            id: "cet4",
            label: "CET-4",
            description: "大学英语四级词库",
            url: "/dicts/CET4_T.json",
            length: 2607,
          },
          {
            id: "cet6",
            label: "CET-6",
            description: "大学英语六级词库",
            url: "/dicts/CET6_T.json",
            length: 2345,
          },
          {
            id: "xinghuoqiaoji_4",
            label: "四级巧记速记",
            description: "四级巧记速记",
            url: "/dicts/xinghuoqiaoji_4.json",
            length: 2522,
          },
          {
            id: "xinghuoqiaoji_6",
            label: "六级巧记速记",
            description: "六级巧记速记",
            url: "/dicts/xinghuoqiaoji_6.json",
            length: 7520,
          },
          {
            id: "cet4-sub",
            label: "CET-4-Sub",
            description: "单词的减法-四级",
            url: "/dicts/DanCiDeJianFa_4.json",
            length: 1957,
          },
          {
            id: "cet6-sub",
            label: "CET-6-Sub",
            description: "单词的减法-六级",
            url: "/dicts/DanCiDeJianFa_6.json",
            length: 1949,
          },
          {
            id: "level4",
            label: "专四",
            description: "英语专业四级词库",
            url: "/dicts/Level4luan_2_T.json",
            length: 4025,
          },
          {
            id: "level8",
            label: "专八",
            description: "英语专业八级词库",
            url: "/dicts/Level8luan_2_T.json",
            length: 12197,
          },
          {
            id: "3000_ClassRoom_English_Words",
            label: "专升本3000词",
            description: "专升本词汇",
            url: "/dicts/3000_ClassRoom_English_Words.json",
            length: 2991,
          },
        ],
      },
      {
        label: "考研",
        children: [
          {
            id: "kaoyan",
            label: "考研",
            description: "研究生英语入学考试词库",
            url: "/dicts/KaoYan_3_T.json",
            length: 3728,
          },
          {
            id: "kaoyan_2024",
            label: "考研 2024",
            description: "研究生英语入学考试词库 2024",
            url: "/dicts/KaoYan_2024.json",
            length: 3731,
          },
          {
            id: "kaoyanshanguo_2023",
            label: "考研闪过 2023",
            description: "高中低频词2023",
            url: "/dicts/KaoYanShanGuo_2023.json",
            length: 1771,
          },
          {
            id: "926",
            label: "考研926词汇",
            description: "926核心词汇",
            url: "/dicts/926.json",
            length: 926,
          },
          {
            id: "dancimimi_1",
            label: "单词的秘密-英语一",
            description: "单词的秘密英语（一）",
            url: "/dicts/DanCiDeMimi_1.json",
            length: 5657,
          },
          {
            id: "dancimimi_2",
            label: "单词的秘密-英语二",
            description: "单词的秘密英语（二）",
            url: "/dicts/DanCiDeMimi_2.json",
            length: 3827,
          },
          {
            id: "2024HongBao T1",
            label: "2024考研英语hongbaoshu(上)",
            description: "2024考研英语hongbaoshu必考词（上）",
            url: "/dicts/2024HongBao_T1.json",
            length: 997,
          },
          {
            id: "2024HongBao T2",
            label: "2024考研英语hongbaoshu(下)",
            description: "2024考研英语hongbaoshu必考词（下）",
            url: "/dicts/2024HongBao_T2.json",
            length: 854,
          },
          {
            id: "hongbaoshu-2026",
            label: "2026考研英语 hongbaoshu",
            description: "2026 考研词汇 (必考词+基础词+超纲词）",
            url: "/dicts/hongbaoshu-2026.json",
            length: 4858,
          },
          {
            id: "English_II",
            label: "英语二单词书",
            description: "考研英语二单词书",
            url: "/dicts/English_II.json",
            length: 4559,
          },
          {
            id: "kaoyanshanguo2025",
            label: "考研 shanguo 2025",
            description: "考研 shanguo 2025",
            url: "/dicts/kaoyanshanguo2025.json",
            length: 2257,
          },
          {
            id: "2025KaoYanHongBaoShu",
            label: "2025考研英语词汇hongbao书",
            description: "2025考研英语词汇hongbao书",
            url: "/dicts/2025KaoYanHongBaoShu.json",
            length: 6705,
          },
        ],
      },
      {
        label: "PET",
        children: [
          {
            id: "pets3",
            label: "PETS",
            description: "全国英语等级考试常考词汇",
            url: "/dicts/PETS_3.json",
            length: 1942,
          },
          {
            id: "pets3-2023",
            label: "PETS-2023",
            description: "全国英语等级考试常考词汇",
            url: "/dicts/PETS3-2023.json",
            length: 4449,
          },
        ],
      },
      {
        label: "自考英语二",
        children: [
          {
            id: "self-study_English1",
            label: "自考1800高频单词",
            description: "自考1800高频单词",
            url: "/dicts/self-study_English1.json",
            length: 1800,
          },
          {
            id: "self-study_English2",
            label: "自考英语二高频悠悠单词",
            description: "自考英语二高频悠悠单词",
            url: "/dicts/self-study_English2.json",
            length: 2181,
          },
          {
            id: "self-study_English3",
            label: "自考英语二完整单词",
            description: "00015自考英语二完整单词书",
            url: "/dicts/self-study_English3.json",
            length: 4603,
          },
        ],
      },
      {
        label: "其他",
        children: [
          {
            id: "coca_20000",
            label: "COCA20000词",
            description: "COCA20000词",
            url: "/dicts/coca20000.json",
            length: 20199,
          },
          {
            id: "4000_Essential_English_Words1",
            label: "Essential Words",
            description: "4000 Essential English Words meaning",
            url: "/dicts/4000_Essential_English_Words-meaning.json",
            length: 3600,
          },
          {
            id: "4000_Essential_English_Words2",
            label: "Essential Words",
            description: "4000 Essential English Words sentence",
            url: "/dicts/4000_Essential_English_Words-sentence.json",
            length: 3600,
          },
          {
            id: "longman_communication_3000_words",
            label: "Longman Communication 3000",
            description:
              "Most frequent words in both spoken and written English",
            url: "/dicts/Longman_Communication_3000.json",
            length: 3168,
          },
          {
            id: "top_2000_English_Words",
            label: "Top 2000 words",
            description: "with highest frequency",
            url: "/dicts/top2000words.json",
            length: 1867,
          },
          {
            id: "top_1500_nouns_Words",
            label: "Top 1500 Nouns",
            description: "with highest frequency",
            url: "/dicts/Top1500NounWords.json",
            length: 1525,
          },
          {
            id: "top_1000_verb_Words",
            label: "Top 1000 Verbs",
            description: "with highest frequency",
            url: "/dicts/Top1000VerbWords.json",
            length: 1011,
          },
          {
            id: "top_500_Adj_Words",
            label: "Top 500 adj.",
            description: "with highest frequency",
            url: "/dicts/Top500AdjectiveWords.json",
            length: 527,
          },
          {
            id: "top_250_Adv_Words",
            label: "Top 250 adv.",
            description: "with highest frequency",
            url: "/dicts/Top250AdverbWords.json",
            length: 255,
          },
          {
            id: "top_60_Pronouns",
            label: "Top 60 pron.",
            description: "with highest frequency",
            url: "/dicts/Top60Pronouns.json",
            length: 59,
          },
          {
            id: "top_50_Prepositions",
            label: "Top 50 prep.",
            description: "with highest frequency",
            url: "/dicts/Top50Prepositions.json",
            length: 46,
          },
          {
            id: "suffix word",
            label: "suffix word",
            description: "common suffix",
            url: "/dicts/suffix_word.json",
            length: 126,
          },
          {
            id: "word roots1",
            label: "word roots1",
            description: "common roots",
            url: "/dicts/word_roots1.json",
            length: 369,
          },
          {
            id: "adult self-study examination",
            label: "专升本词汇",
            description: "专升本词汇",
            url: "/dicts/adult-self-study-examination.json",
            length: 3692,
          },
          {
            id: "zhuan-cha-ben-ying-yu",
            label: "专插本英语词汇",
            description: "专插本英语词汇",
            url: "/dicts/zhuan-cha-ben.json",
            length: 3216,
          },
          {
            id: "zhuan-sheng-ben-xue-shi",
            label: "专升本学士学位的英语",
            description: "专升本学士学位的英语",
            url: "/dicts/xueshiyingyu.json",
            length: 897,
          },
          {
            id: "Oxford5000",
            label: "牛津5000词",
            description: "牛津5000词",
            url: "/dicts/Oxford5000.json",
            length: 5836,
          },
          {
            id: "Merriam_Webster_sVocabularyBuilder",
            label: "韦氏词根词典",
            description: "韦氏词根词典",
            url: "/dicts/Merriam_Webster_sVocabularyBuilder.json",
            length: 1191,
          },
          {
            id: "tingshuokaoshi",
            label: "听说考试常见词汇",
            description: "听说考试16个场景常见词汇量",
            url: "/dicts/tingshuokaoshi.json",
            length: 556,
          },
          {
            id: "frequently_used_words01",
            label: "超频单词level 1",
            description: "超频单词level 1",
            url: "/dicts/frequently_used_word01.json",
            length: 679,
          },
          {
            id: "frequently_used_words03",
            label: "超频单词level 2",
            description: "超频单词level 2",
            url: "/dicts/frequently_used_word02.json",
            length: 1040,
          },
          {
            id: "frequently_used_words03",
            label: "超频单词level 3",
            description: "超频单词level 3",
            url: "/dicts/frequently_used_word03.json",
            length: 1435,
          },
          {
            id: "Macmillan7000",
            label: "麦克米伦7000",
            description: "麦克米伦7000",
            url: "/dicts/Macmillan7000.json",
            length: 6268,
          },
        ],
      },
    ],
  },
  {
    label: "国际考试",
    children: [
      {
        label: "TOEFL",
        children: [
          {
            id: "TOEFL_ZhangHongYan",
            label: "ZhangHongYan的TOEFL词汇书",
            description: "ZhangHongYan的TOEFL词汇书-词以类记",
            url: "/dicts/TOEFL_ZhangHongYan.json",
            length: 4032,
          },
          {
            id: "toefl",
            label: "TOEFL",
            description: "托福考试常见词",
            url: "/dicts/TOEFL_3_T.json",
            length: 4264,
          },
        ],
      },
      {
        label: "PET",
        children: [
          {
            id: "pet-2024",
            label: "PET-2024",
            description: "剑桥英语 - 2024",
            url: "/dicts/pet-vacabulary-list-2024.json",
            length: 1871,
          },
        ],
      },
      {
        label: "GMAT",
        children: [
          {
            id: "gmat",
            label: "GMAT",
            description: "GMAT 词库",
            url: "/dicts/GMAT_3_T.json",
            length: 3047,
          },
        ],
      },
      {
        label: "GRE",
        children: [
          {
            id: "gre",
            label: "GRE",
            description: "GRE 词库",
            url: "/dicts/GRE_3_T.json",
            length: 6515,
          },
          {
            id: "gre1500",
            label: "GRE重点1500词-fen哥",
            description: "GRE & TEM8 重叠高频词汇",
            url: "/dicts/GRE_1500.json",
            length: 1533,
          },
          {
            id: "gre3000",
            label: "GRE3000",
            description: "GRE3000 词库",
            url: "/dicts/GRE3000_3_T.json",
            length: 3041,
          },
          {
            id: "GRE-computer-based-test",
            label: "GRE机经词汇",
            description: "GRE机经词汇",
            url: "/dicts/GRE-computer-based-test.json",
            length: 1451,
          },
          {
            id: "ZaiYaoNiMing_GRE3000",
            label: "再要你命GRE3000",
            description: "再要你命GRE3000词库-有词性新版",
            url: "/dicts/ZaiYaoNiMing_GRE3000.json",
            length: 3041,
          },
          {
            id: "GRE_equivalent",
            label: "GRE等价词",
            description: "GRE等价词",
            url: "/dicts/GRE_equivalent.json",
            length: 827,
          },
          {
            id: "GRE_ciyileiji",
            label: "GRE词以类记",
            description: "GRE词以类记",
            url: "/dicts/gre-ciyileiji.json",
            length: 8785,
          },
        ],
      },
      {
        label: "IELTS",
        children: [
          {
            id: "IELTS_tinglichangjing",
            label: "雅思听力场景词汇",
            description: "雅思听力场景词汇",
            url: "/dicts/IELTS_tinglichangjing.json",
            length: 1204,
          },
          {
            id: "ielts_disorder",
            label: "IELTS乱序完整版",
            description: "IELTS乱序完整版",
            url: "/dicts/IELTS_disorder.json",
            length: 9389,
          },
          {
            id: "ielts_order",
            label: "IELTS顺序完整版",
            description: "IELTS顺序完整版",
            url: "/dicts/IELTS_order.json",
            length: 9389,
          },
          {
            id: "ielts",
            label: "IELTS",
            description: "雅思词库",
            url: "/dicts/IELTS_3_T.json",
            length: 3575,
          },
          {
            id: "heqiong",
            label: "heQiong雅思听力必考词汇",
            description: "综合测试",
            url: "/dicts/HeQiong_IELTS.json",
            length: 2529,
          },
          {
            id: "ieltsWang3",
            label: "雅思wang C3",
            description: "雅思听力特别名词语料库",
            url: "/dicts/IELTS_WANG_3.json",
            length: 1135,
          },
          {
            id: "ieltsWang4",
            label: "雅思wang C4",
            description: "雅思听力形容词副词语料库",
            url: "/dicts/IELTS_WANG_4.json",
            length: 346,
          },
          {
            id: "ieltsWang5",
            label: "雅思wang C5",
            description: "吞音连读混合训练语料库",
            url: "/dicts/IELTS_WANG_5.json",
            length: 1569,
          },
          {
            id: "ieltsWang11",
            label: "雅思wang C11",
            description: "综合测试",
            url: "/dicts/IELTS_WANG_11.json",
            length: 1738,
          },
          {
            id: "DuckCircle_IELTS",
            label: "鸭圈雅思核心词",
            description: "鸭圈雅思核心词",
            url: "/dicts/DuckCircle_IELTS.json",
            length: 2644,
          },
          {
            id: "IELTSVocabularyBible",
            label: "雅思词汇真经",
            description: "雅思词汇真经",
            url: "/dicts/IELTSVocabularyBible.json",
            length: 3673,
          },
          {
            id: "IELTS-807",
            label: "雅思 wanglu 807",
            description: "雅思 wanglu 807",
            url: "/dicts/ielts-807.json",
            length: 4340,
          },
          {
            id: "ielts-real-high",
            label: "雅思 real 词汇 高频",
            description: "雅思 real 词汇（高频词汇）",
            url: "/dicts/ielts-real-high.json",
            length: 524,
          },
          {
            id: "ielts-real-5",
            label: "雅思 real 词汇 5",
            description: "雅思 real 词汇 （5频词汇及变频）",
            url: "/dicts/ielts-real-5.json",
            length: 183,
          },
          {
            id: "ielts-real-4",
            label: "雅思 real 词汇 4",
            description: "雅思 real 词汇 （4频词汇及变频）",
            url: "/dicts/ielts-real-4.json",
            length: 201,
          },
          {
            id: "ielts-real-3",
            label: "雅思 real 词汇 3",
            description: "雅思 real 词汇 （3频词汇及变频）",
            url: "/dicts/ielts-real-3.json",
            length: 256,
          },
          {
            id: "ielts-real-2",
            label: "雅思 real 词汇 2",
            description: "雅思 real 词汇 （2频词汇及变频）",
            url: "/dicts/ielts-real-2.json",
            length: 402,
          },
          {
            id: "ielts-real-1",
            label: "雅思 real 词汇 1",
            description: "雅思 real 词汇 （1频词汇及变频）",
            url: "/dicts/ielts-real-1.json",
            length: 737,
          },
          {
            id: "IELTS9988wangyong",
            label: "雅思9988wangyong",
            description: "雅思9988wangyong",
            url: "/dicts/IELTS9988wangyong.json",
            length: 3698,
          },
          {
            id: "IELTSKingLu807",
            label: "wanglu807雅思词汇听力第2版",
            description: "wanglu807雅思词汇听力第2版",
            url: "/dicts/IELTSKingLu807.json",
            length: 1916,
          },
          {
            id: "IELTSXDF7000",
            label: "100个句子记完7000个雅思单词",
            description: "xdf 100个句子记完7000个雅思单词 词汇表",
            url: "/dicts/IELTS_XDF_7000.json",
            length: 5567,
          },
          {
            id: "IELTS-oral-900",
            label: "雅思口语 900 beta版",
            description: "雅思口语 900 句, 需在 qwerty 设置中调小英语字体",
            url: "/dicts/IELTS-oral-900.json",
            length: 900,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task1",
            label: "xdf听力 雅思中级直通车 day1",
            description: "xdf听力 雅思中级直通车 day1",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task1.json",
            length: 44,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task2",
            label: "xdf听力 雅思中级直通车 day2",
            description: "xdf听力 雅思中级直通车 day2",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task2.json",
            length: 33,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task3",
            label: "xdf听力 雅思中级直通车 day3",
            description: "xdf听力 雅思中级直通车 day3",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task3.json",
            length: 33,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task4",
            label: "xdf听力 雅思中级直通车 day4",
            description: "xdf听力 雅思中级直通车 day4",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task4.json",
            length: 33,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task5",
            label: "xdf听力 雅思中级直通车 day5",
            description: "xdf听力 雅思中级直通车 day5",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task5.json",
            length: 38,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task6",
            label: "xdf听力 雅思中级直通车 day6",
            description: "xdf听力 雅思中级直通车 day6",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task6.json",
            length: 33,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task7",
            label: "xdf听力 雅思中级直通车 day7",
            description: "xdf听力 雅思中级直通车 day7",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task7.json",
            length: 39,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task8",
            label: "xdf听力 雅思中级直通车 day8",
            description: "xdf听力 雅思中级直通车 day8",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task8.json",
            length: 32,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task9",
            label: "xdf听力 雅思中级直通车 day9",
            description: "xdf听力 雅思中级直通车 day9",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task9.json",
            length: 46,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task10",
            label: "xdf听力 雅思中级直通车 day10",
            description: "xdf听力 雅思中级直通车 day10",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task10.json",
            length: 44,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task11",
            label: "xdf听力 雅思中级直通车 day11",
            description: "xdf听力 雅思中级直通车 day11",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task11.json",
            length: 36,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task12",
            label: "xdf听力 雅思中级直通车 day12",
            description: "xdf听力 雅思中级直通车 day12",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task12.json",
            length: 45,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task13",
            label: "xdf听力 雅思中级直通车 day13",
            description: "xdf听力 雅思中级直通车 day13",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task13.json",
            length: 49,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task14",
            label: "xdf听力 雅思中级直通车 day14",
            description: "xdf听力 雅思中级直通车 day14",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task14.json",
            length: 46,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task15",
            label: "xdf听力 雅思中级直通车 day15",
            description: "xdf听力 雅思中级直通车 day15",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task15.json",
            length: 29,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task16",
            label: "xdf听力 雅思中级直通车 day16",
            description: "xdf听力 雅思中级直通车 day16",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task16.json",
            length: 42,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task17",
            label: "xdf听力 雅思中级直通车 day17",
            description: "xdf听力 雅思中级直通车 day17",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task17.json",
            length: 22,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task18",
            label: "xdf听力 雅思中级直通车 day18",
            description: "xdf听力 雅思中级直通车 day18",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task18.json",
            length: 37,
          },
          {
            id: "IELTS-listening-NeworientalDirect-Task19",
            label: "xdf听力 雅思中级直通车 day19",
            description: "xdf听力 雅思中级直通车 day19",
            url: "/dicts/IELTS-listening-NewOrientalDirect-Task19.json",
            length: 26,
          },
          {
            id: "IELTS-listening-18-days-1",
            label: "雅思听力词汇18天 day1",
            description: "雅思听力词汇18天 day1",
            url: "/dicts/IELTS-listening-18days-day1.json",
            length: 74,
          },
          {
            id: "IELTS-listening-18-days-2",
            label: "雅思听力词汇18天 day2",
            description: "雅思听力词汇18天 day2",
            url: "/dicts/IELTS-listening-18days-day2.json",
            length: 77,
          },
          {
            id: "IELTS-listening-18-days-3",
            label: "雅思听力词汇18天 day3",
            description: "雅思听力词汇18天 day3",
            url: "/dicts/IELTS-listening-18days-day3.json",
            length: 77,
          },
          {
            id: "IELTS-listening-18-days-4",
            label: "雅思听力词汇18天 day4",
            description: "雅思听力词汇18天 day4",
            url: "/dicts/IELTS-listening-18days-day4.json",
            length: 73,
          },
          {
            id: "IELTS-listening-18-days-5",
            label: "雅思听力词汇18天 day5",
            description: "雅思听力词汇18天 day5",
            url: "/dicts/IELTS-listening-18days-day5.json",
            length: 76,
          },
          {
            id: "IELTS-listening-18-days-6",
            label: "雅思听力词汇18天 day6",
            description: "雅思听力词汇18天 day6",
            url: "/dicts/IELTS-listening-18days-day6.json",
            length: 77,
          },
          {
            id: "IELTS-listening-18-days-7",
            label: "雅思听力词汇18天 day7",
            description: "雅思听力词汇18天 day7",
            url: "/dicts/IELTS-listening-18days-day7.json",
            length: 75,
          },
          {
            id: "IELTS-listening-18-days-8",
            label: "雅思听力词汇18天 day8",
            description: "雅思听力词汇18天 day8",
            url: "/dicts/IELTS-listening-18days-day8.json",
            length: 75,
          },
          {
            id: "IELTS-listening-18-days-9",
            label: "雅思听力词汇18天 day9",
            description: "雅思听力词汇18天 day9",
            url: "/dicts/IELTS-listening-18days-day9.json",
            length: 76,
          },
          {
            id: "IELTS-listening-18-days-10",
            label: "雅思听力词汇18天 day10",
            description: "雅思听力词汇18天 day10",
            url: "/dicts/IELTS-listening-18days-day10.json",
            length: 33,
          },
          {
            id: "IELTS-listening-18-days-11",
            label: "雅思听力词汇18天 day11",
            description: "雅思听力词汇18天 day11",
            url: "/dicts/IELTS-listening-18days-day11.json",
            length: 52,
          },
          {
            id: "IELTS-listening-18-days-12",
            label: "雅思听力词汇18天 day12",
            description: "雅思听力词汇18天 day12",
            url: "/dicts/IELTS-listening-18days-day12.json",
            length: 77,
          },
          {
            id: "IELTS-listening-18-days-13",
            label: "雅思听力词汇18天 day13",
            description: "雅思听力词汇18天 day13",
            url: "/dicts/IELTS-listening-18days-day13.json",
            length: 78,
          },
          {
            id: "IELTS-listening-18-days-14",
            label: "雅思听力词汇18天 day14",
            description: "雅思听力词汇18天 day14",
            url: "/dicts/IELTS-listening-18days-day14.json",
            length: 76,
          },
          {
            id: "IELTS-listening-18-days-15",
            label: "雅思听力词汇18天 day15",
            description: "雅思听力词汇18天 day15",
            url: "/dicts/IELTS-listening-18days-day15.json",
            length: 77,
          },
          {
            id: "IELTS-listening-18-days-16",
            label: "雅思听力词汇18天 day16",
            description: "雅思听力词汇18天 day16",
            url: "/dicts/IELTS-listening-18days-day16.json",
            length: 77,
          },
          {
            id: "IELTS-listening-18-days-17",
            label: "雅思听力词汇18天 day17",
            description: "雅思听力词汇18天 day17",
            url: "/dicts/IELTS-listening-18days-day17.json",
            length: 46,
          },
          {
            id: "IELTS-listening-18-days-18",
            label: "雅思听力词汇18天 day18",
            description: "雅思听力词汇18天 day18",
            url: "/dicts/IELTS-listening-18days-day18.json",
            length: 76,
          },
        ],
      },
      {
        label: "KET",
        children: [
          {
            id: "ket",
            label: "KET",
            description: "KET 2021单词",
            url: "./dicts/ket2021.json",
            length: 1147,
          },
        ],
      },
      {
        label: "SAT",
        children: [
          {
            id: "sat",
            label: "SAT",
            description: "美国 SAT 考试词库",
            url: "/dicts/SAT_3_T.json",
            length: 4464,
          },
          {
            id: "SATen",
            label: "SAT en-en",
            description: "SAT英英",
            url: "/dicts/SATen.json",
            length: 2681,
          },
        ],
      },
      {
        label: "BEC",
        children: [
          {
            id: "bec2",
            label: "商务英语",
            description: "商务英语常见词",
            url: "/dicts/BEC_2_T.json",
            length: 2753,
          },
          {
            id: "bec3",
            label: "BEC",
            description: "BEC考试常见词",
            url: "/dicts/BEC_3_T.json",
            length: 2825,
          },
        ],
      },
      {
        label: "PTE",
        children: [
          {
            id: "PTE_junior",
            label: "PTE 基础词汇",
            description: "",
            url: "/dicts/PTE_junior.json",
            length: 2651,
          },
          {
            id: "PTE_senior",
            label: "PTE 高阶词汇",
            description: "",
            url: "/dicts/PTE_senior.json",
            length: 3170,
          },
          {
            id: "PTE_FIB_R_junior",
            label: "阅读 FIB 基础机经词汇",
            description: "",
            url: "/dicts/PTE_FIB_R_junior.json",
            length: 941,
          },
          {
            id: "PTE_FIB_R_senior",
            label: "阅读 FIB 高阶机经词汇",
            description: "",
            url: "/dicts/PTE_FIB_R_senior.json",
            length: 1272,
          },
          {
            id: "PTE_WFD",
            label: "WFD 机经词汇",
            description: "",
            url: "/dicts/PTE_WFD.json",
            length: 1212,
          },
          {
            id: "PTE_FIB_L",
            label: "听力 FIB 机经词汇",
            description: "",
            url: "/dicts/PTE_FIB_L.json",
            length: 646,
          },
          {
            id: "PTE_Basic_apeuni",
            label: "PTE 基础词汇 xingji",
            description: "",
            url: "/dicts/PTE_Basic_apeuni.json",
            length: 2652,
          },
          {
            id: "PTE_Advanced_apeuni.json",
            label: "PTE 高阶词汇 xingji",
            description: "",
            url: "/dicts/PTE_Advanced_apeuni.json",
            length: 3169,
          },
          {
            id: "PTE_Read_apeuni.json",
            label: "PTE 阅读FIB机经词汇 xingji",
            description: "",
            url: "/dicts/PTE_Read_apeuni.json",
            length: 630,
          },
          {
            id: "PTE_Listening_apeuni.json",
            label: "PTE 听力FIB机经词汇 xingji",
            description: "",
            url: "/dicts/PTE_Listening_apeuni.json",
            length: 674,
          },
          {
            id: "Common-Phrases-PTE-Unofficial",
            label: "PTE 常用短语 (非官方)",
            description: "PTE 常用短语",
            url: "/dicts/Common-Phrases-PTE-Unofficial.json",
            length: 274,
          },
        ],
      },
      {
        label: "TOEIC",
        children: [
          {
            id: "TOEIC",
            label: "TOEIC 词汇",
            description: "",
            url: "/dicts/TOEIC.json",
            length: 1694,
          },
        ],
      },
      {
        label: "CEFR",
        children: [
          {
            id: "Duolingo_Vocabulary_B1",
            label: "多邻国分级词汇B1",
            description: "多邻国分级词汇B1",
            url: "/dicts/Duolingo_Vocabulary_B1.json",
            length: 801,
          },
          {
            id: "Duolingo_Vocabulary_B2",
            label: "多邻国分级词汇B2",
            description: "多邻国分级词汇B2",
            url: "/dicts/Duolingo_Vocabulary_B2.json",
            length: 1423,
          },
          {
            id: "Duolingo_Vocabulary_C1",
            label: "多邻国分级词汇C1",
            description: "多邻国分级词汇C1",
            url: "/dicts/Duolingo_Vocabulary_C1.json",
            length: 1314,
          },
        ],
      },
      {
        label: "牛津版",
        children: [
          {
            id: "Oxford3000",
            label: "牛津3000词",
            description: "牛津3000词",
            url: "/dicts/Oxford3000.json",
            length: 1342,
          },
          {
            id: "Oxford5000",
            label: "牛津5000词",
            description: "牛津5000词",
            url: "/dicts/Oxford5000.json",
            length: 5836,
          },
        ],
      },
      {
        label: "其他",
        children: [
          {
            id: "voa",
            label: "VOA 基础词库",
            description: "VOA 基础词库",
            url: "/dicts/voa.json",
            length: 1505,
          },
        ],
      },
      {
        label: "FCE",
        children: [
          {
            id: "Common-Phrases-FCE-Unofficial",
            label: "FCE 常用短语 (非官方)",
            description: "FCE 常用短语",
            url: "/dicts/Common-Phrases-FCE-Unofficial.json",
            length: 438,
          },
        ],
      },
    ],
  },
  {
    label: "青少年英语",
    children: [
      {
        label: "通用",
        children: [
          {
            id: "gaokao3500",
            label: "高考 3500 词",
            description: "高考常见词 3500",
            url: "/dicts/GaoKao_3500.json",
            length: 3893,
          },
          {
            id: "gaokaozhentihexin",
            label: "高考历年真题核心高频",
            description: "高考历年真题核心高频",
            url: "/dicts/GaoKaoZhenTiHeXinGaoPin.json",
            length: 799,
          },
          {
            id: "gaokao-yuedu-gaopin",
            label: "高考英语阅读高频词汇",
            description: "高考英语阅读高频词汇",
            url: "/dicts/gaokao-yuedu-gaopin.json",
            length: 688,
          },
          {
            id: "zhongkaohexin",
            label: "中考核心词",
            description: "中考核心词",
            url: "/dicts/ZhongKaoHeXin.json",
            length: 2140,
          },
        ],
      },
      {
        label: "新概念英语",
        children: [
          {
            id: "nce1",
            label: "新概念英语-1",
            description: "新概念英语第一册",
            url: "/dicts/NCE_1.json",
            length: 900,
          },
          {
            id: "nce2",
            label: "新概念英语-2",
            description: "新概念英语第二册",
            url: "/dicts/NCE_2.json",
            length: 858,
          },
          {
            id: "nce3",
            label: "新概念英语-3",
            description: "新概念英语第三册",
            url: "/dicts/NCE_3.json",
            length: 1052,
          },
          {
            id: "nce4",
            label: "新概念英语-4",
            description: "新概念英语第四册",
            url: "/dicts/NCE_4.json",
            length: 784,
          },
          {
            id: "nce-new-1",
            label: "新概念英语(新版)-1",
            description: "新概念英语新版第一册",
            url: "/dicts/nce-new-1.json",
            length: 908,
          },
          {
            id: "nce-new-2",
            label: "新概念英语(新版)-2",
            description: "新概念英语新版第二册",
            url: "/dicts/nce-new-2.json",
            length: 862,
          },
          {
            id: "nce-new-3",
            label: "新概念英语(新版)-3",
            description: "新概念英语新版第三册",
            url: "/dicts/nce-new-3.json",
            length: 1062,
          },
          {
            id: "nce-new-4",
            label: "新概念英语(新版)-4",
            description: "新概念英语新版第四册",
            url: "/dicts/nce-new-4.json",
            length: 793,
          },
        ],
      },
      {
        label: "牛津版",
        children: [
          {
            id: "SHjuniormiddleOxford",
            label: "上海初中牛津词汇",
            description: "上海初中牛津词汇",
            url: "/dicts/OxfordVocabulary_juniorMiddleSH.json",
            length: 1270,
          },
        ],
      },
      {
        label: "人教版",
        children: [
          {
            id: "san1",
            label: "三年级上",
            description: "人教版三年级上册",
            url: "/dicts/PEPXiaoXue3_1_T.json",
            length: 64,
          },
          {
            id: "san2",
            label: "三年级下",
            description: "人教版三年级下册",
            url: "/dicts/PEPXiaoXue3_2_T.json",
            length: 72,
          },
          {
            id: "si1",
            label: "四年级上",
            description: "人教版四年级上册",
            url: "/dicts/PEPXiaoXue4_1_T.json",
            length: 84,
          },
          {
            id: "si2",
            label: "四年级下",
            description: "人教版四年级下册",
            url: "/dicts/PEPXiaoXue4_2_T.json",
            length: 104,
          },
          {
            id: "wu1",
            label: "五年级上",
            description: "人教版五年级上册",
            url: "/dicts/PEPXiaoXue5_1_T.json",
            length: 131,
          },
          {
            id: "wu2",
            label: "五年级下",
            description: "人教版五年级下册",
            url: "/dicts/PEPXiaoXue5_2_T.json",
            length: 156,
          },
          {
            id: "liu1",
            label: "六年级上",
            description: "人教版六年级上册",
            url: "/dicts/PEPXiaoXue6_1_T.json",
            length: 130,
          },
          {
            id: "liu2",
            label: "六年级下",
            description: "人教版六年级下册",
            url: "/dicts/PEPXiaoXue6_2_T.json",
            length: 108,
          },
          {
            id: "pep-sl-yi1",
            label: "人教版(新起点)一年级上",
            description: "人教版一年级上册",
            url: "/dicts/PEP_SL_XiaoXue1_1_t.json",
            length: 52,
          },
          {
            id: "pep-sl-yi2",
            label: "人教版(新起点)一年级下",
            description: "人教版一年级下册",
            url: "/dicts/PEP_SL_XiaoXue1_2_t.json",
            length: 45,
          },
          {
            id: "pep-sl-er1",
            label: "人教版(新起点)二年级上",
            description: "人教版二年级上册",
            url: "/dicts/PEP_SL_XiaoXue2_1_t.json",
            length: 54,
          },
          {
            id: "pep-sl-er2",
            label: "人教版(新起点)二年级下",
            description: "人教版二年级下册",
            url: "/dicts/PEP_SL_XiaoXue2_2_t.json",
            length: 55,
          },
          {
            id: "pep-sl-san1",
            label: "人教版(新起点)三年级上",
            description: "人教版三年级上册",
            url: "/dicts/PEP_SL_XiaoXue3_1_t.json",
            length: 103,
          },
          {
            id: "pep-sl-san2",
            label: "人教版(新起点)三年级下",
            description: "人教版三年级下册",
            url: "/dicts/PEP_SL_XiaoXue3_2_t.json",
            length: 84,
          },
          {
            id: "pep-sl-si1",
            label: "人教版(新起点)四年级上",
            description: "人教版四年级上册",
            url: "/dicts/PEP_SL_XiaoXue4_1_t.json",
            length: 115,
          },
          {
            id: "pep-sl-si2",
            label: "人教版(新起点)四年级下",
            description: "人教版四年级下册",
            url: "/dicts/PEP_SL_XiaoXue4_2_t.json",
            length: 87,
          },
          {
            id: "pep-sl-wu1",
            label: "人教版(新起点)五年级上",
            description: "人教版五年级上册",
            url: "/dicts/PEP_SL_XiaoXue5_1_t.json",
            length: 66,
          },
          {
            id: "pep-sl-wu2",
            label: "人教版(新起点)五年级下",
            description: "人教版五年级下册",
            url: "/dicts/PEP_SL_XiaoXue5_2_t.json",
            length: 96,
          },
          {
            id: "pep-sl-liu1",
            label: "人教版(新起点)六年级上",
            description: "人教版六年级上册",
            url: "/dicts/PEP_SL_XiaoXue6_1_t.json",
            length: 102,
          },
          {
            id: "pep-sl-liu2",
            label: "人教版(新起点)六年级下",
            description: "人教版六年级下册",
            url: "/dicts/PEP_SL_XiaoXue6_2_t.json",
            length: 41,
          },
          {
            id: "qi1",
            label: "七年级上",
            description: "人教版七年级上册",
            url: "/dicts/PEPChuZhong7_1_T.json",
            length: 392,
          },
          {
            id: "qi2",
            label: "七年级下",
            description: "人教版七年级下册",
            url: "/dicts/PEPChuZhong7_2_T.json",
            length: 492,
          },
          {
            id: "ba1",
            label: "八年级上",
            description: "人教版八年级上册",
            url: "/dicts/PEPChuZhong8_1_T.json",
            length: 419,
          },
          {
            id: "ba2",
            label: "八年级下",
            description: "人教版八年级下册",
            url: "/dicts/PEPChuZhong8_2_T.json",
            length: 466,
          },
          {
            id: "jiu",
            label: "九年级",
            description: "人教版九年级全册",
            url: "/dicts/PEPChuZhong9_1_T.json",
            length: 551,
          },
          {
            id: "renjiaogaozhong1",
            label: "高中必修1",
            description: "人教版高中必修1",
            url: "/dicts/PEPGaoZhong_1_T.json",
            length: 311,
          },
          {
            id: "renjiaogaozhong2",
            label: "高中必修2",
            description: "人教版高中必修2",
            url: "/dicts/PEPGaoZhong_2_T.json",
            length: 319,
          },
          {
            id: "renjiaogaozhong3",
            label: "高中必修3",
            description: "人教版高中必修3",
            url: "/dicts/PEPGaoZhong_3_T.json",
            length: 366,
          },
          {
            id: "renjiaogaozhong4",
            label: "高中必修4",
            description: "人教版高中必修4",
            url: "/dicts/PEPGaoZhong_4_T.json",
            length: 307,
          },
          {
            id: "renjiaogaozhong5",
            label: "高中必修5",
            description: "人教版高中必修5",
            url: "/dicts/PEPGaoZhong_5_T.json",
            length: 357,
          },
          {
            id: "renjiaogaozhong6",
            label: "高中选修6",
            description: "人教版高中选修6",
            url: "/dicts/PEPGaoZhong_6_T.json",
            length: 391,
          },
          {
            id: "renjiaogaozhong7",
            label: "高中选修7",
            description: "人教版高中选修7",
            url: "/dicts/PEPGaoZhong_7_T.json",
            length: 384,
          },
          {
            id: "renjiaogaozhong8",
            label: "高中选修8",
            description: "人教版高中选修8",
            url: "/dicts/PEPGaoZhong_8_T.json",
            length: 420,
          },
          {
            id: "renjiaogaozhong9",
            label: "高中选修9",
            description: "人教版高中选修9",
            url: "/dicts/PEPGaoZhong_9_T.json",
            length: 352,
          },
          {
            id: "renjiaogaozhong10",
            label: "高中选修10",
            description: "人教版高中选修10",
            url: "/dicts/PEPGaoZhong_10_T.json",
            length: 361,
          },
          {
            id: "renjiaogaozhong11",
            label: "高中选修11",
            description: "人教版高中选修11",
            url: "/dicts/PEPGaoZhong_11_T.json",
            length: 309,
          },
        ],
      },
      {
        label: "外研版",
        children: [
          {
            id: "waiyan1",
            label: "外研七年级上册",
            description: "外研版七年级上册",
            url: "/dicts/WaiYanSheChuZhong_1_T.json",
            length: 629,
          },
          {
            id: "new-waiyan1",
            label: "新外研七年级上册",
            description: "新外研版七年级上册",
            url: "/dicts/Newwaiyan7-1.json",
            length: 294,
          },
          {
            id: "new-waiyan2",
            label: "新外研七年级下册",
            description: "新外研版七年级下册",
            url: "/dicts/Newwaiyan7-2.json",
            length: 305,
          },
          {
            id: "waiyan2",
            label: "外研七年级下册",
            description: "外研版七年级下册",
            url: "/dicts/WaiYanSheChuZhong_2_T.json",
            length: 438,
          },
          {
            id: "waiyan3",
            label: "外研八年级上册",
            description: "外研版八年级上册",
            url: "/dicts/WaiYanSheChuZhong_3_T.json",
            length: 320,
          },
          {
            id: "waiyan4",
            label: "外研八年级下册",
            description: "外研版八年级下册",
            url: "/dicts/WaiYanSheChuZhong_4_T.json",
            length: 266,
          },
          {
            id: "waiyan5",
            label: "外研九年级上册",
            description: "外研版九年级上册",
            url: "/dicts/WaiYanSheChuZhong_5_T.json",
            length: 381,
          },
          {
            id: "waiyan6",
            label: "外研九年级下册",
            description: "外研版九年级下册",
            url: "/dicts/WaiYanSheChuZhong_6_T.json",
            length: 128,
          },
          {
            id: "waiyan7",
            label: "外研高中必修1",
            description: "外研高中必修1",
            url: "/dicts/WaiYanSheGaoZhong_1_T.json",
            length: 411,
          },
          {
            id: "waiyan8",
            label: "外研高中必修2",
            description: "外研高中必修2",
            url: "/dicts/WaiYanSheGaoZhong_2_T.json",
            length: 272,
          },
          {
            id: "waiyan9",
            label: "外研一年级上册",
            description: "外研一年级上册",
            url: "/dicts/WaiYanSheChuZhong_1-Volume-up.json",
            length: 138,
          },
          {
            id: "waiyan10",
            label: "外研一年级下册",
            description: "外研一年级下册",
            url: "/dicts/WaiYanSheChuZhong_1-Volume-down.json",
            length: 118,
          },
          {
            id: "waiyan11",
            label: "外研二年级上册",
            description: "外研二年级上册",
            url: "/dicts/WaiYanSheChuZhong_2-Volume-top.json",
            length: 118,
          },
          {
            id: "waiyan12",
            label: "外研二年级下册",
            description: "外研二年级下册",
            url: "/dicts/WaiYanSheChuZhong_2-Volume-down.json",
            length: 110,
          },
          {
            id: "waiyan13",
            label: "外研三年级上册",
            description: "外研三年级上册",
            url: "/dicts/WaiYanSheChuZhong_3-Volume-top.json",
            length: 82,
          },
          {
            id: "waiyan14",
            label: "外研三年级下册",
            description: "外研三年级下册",
            url: "/dicts/WaiYanSheChuZhong_3-Volume-down.json",
            length: 106,
          },
          {
            id: "waiyan15",
            label: "外研四年级上册",
            description: "外研四年级上册",
            url: "/dicts/WaiYanSheChuZhong_4-Volume-top.json",
            length: 116,
          },
          {
            id: "waiyan16",
            label: "外研四年级下册",
            description: "外研四年级下册",
            url: "/dicts/WaiYanSheChuZhong_4-Volume-down.json",
            length: 78,
          },
          {
            id: "waiyan17",
            label: "外研五年级上册",
            description: "外研五年级上册",
            url: "/dicts/WaiYanSheChuZhong_5-Volume-top.json",
            length: 80,
          },
          {
            id: "waiyan18",
            label: "外研五年级下册",
            description: "外研五年级下册",
            url: "/dicts/WaiYanSheChuZhong_5-Volume-down.json",
            length: 72,
          },
          {
            id: "waiyan19",
            label: "外研六年级上册",
            description: "外研六年级上册",
            url: "/dicts/WaiYanSheChuZhong_6-Volume-top.json",
            length: 61,
          },
          {
            id: "waiyan20",
            label: "外研六年级下册",
            description: "外研六年级下册",
            url: "/dicts/WaiYanSheChuZhong_6-Volume-down.json",
            length: 91,
          },
          {
            id: "waiyan3-1",
            label: "外研新起点三年级上册",
            description: "外研新起点三年级上册",
            url: "/dicts/waiyan-xin-3-1.json",
            length: 134,
          },
          {
            id: "waiyan3-2",
            label: "外研新起点三年级下册",
            description: "外研新起点三年级下册",
            url: "/dicts/waiyan-xin-3-2.json",
            length: 156,
          },
          {
            id: "waiyan4-1",
            label: "外研新起点四年级上册",
            description: "外研新起点四年级上册",
            url: "/dicts/waiyan-xin-4-1.json",
            length: 144,
          },
          {
            id: "waiyan4-2",
            label: "外研新起点四年级下册",
            description: "外研新起点四年级下册",
            url: "/dicts/waiyan-xin-4-2.json",
            length: 134,
          },
          {
            id: "waiyan5-1",
            label: "外研新起点五年级上册",
            description: "外研新起点五年级上册",
            url: "/dicts/waiyan-xin-5-1.json",
            length: 152,
          },
          {
            id: "waiyan5-2",
            label: "外研新起点五年级下册",
            description: "外研新起点五年级下册",
            url: "/dicts/waiyan-xin-5-2.json",
            length: 147,
          },
          {
            id: "waiyan6-1",
            label: "外研新起点六年级上册",
            description: "外研新起点六年级上册",
            url: "/dicts/waiyan-xin-6-1.json",
            length: 83,
          },
          {
            id: "waiyan6-2",
            label: "外研新起点六年级下册",
            description: "外研新起点六年级下册",
            url: "/dicts/waiyan-xin-6-2.json",
            length: 105,
          },
        ],
      },
      {
        label: "上海版",
        children: [
          {
            id: "shanghai-6-2word",
            label: "上海新教材六年级下",
            description: "上海新教材六年级下",
            url: "/dicts/shanghai-6-2-word.json",
            length: 274,
          },
        ],
      },
      {
        label: "译林版",
        children: [
          {
            id: "Yilin1",
            label: "高中必修1",
            description: "译林版高中必修1",
            url: "./dicts/YiLin_1.json",
            length: 276,
          },
          {
            id: "Yilin2",
            label: "高中必修2",
            description: "译林版高中必修2",
            url: "./dicts/YiLin_2.json",
            length: 297,
          },
          {
            id: "Yilin3",
            label: "高中必修3",
            description: "译林版高中必修3",
            url: "./dicts/YiLin_3.json",
            length: 295,
          },
        ],
      },
      {
        label: "北师大",
        children: [
          {
            id: "beishi1",
            label: "高中必修1",
            description: "北师大版高中必修1",
            url: "/dicts/BeiShiGaoZhong_1_T.json",
            length: 226,
          },
          {
            id: "beishi2",
            label: "高中必修2",
            description: "北师大版高中必修2",
            url: "/dicts/BeiShiGaoZhong_2_T.json",
            length: 244,
          },
          {
            id: "beishi3",
            label: "高中必修3",
            description: "北师大版高中必修3",
            url: "/dicts/BeiShiGaoZhong_3_T.json",
            length: 295,
          },
          {
            id: "beishi4",
            label: "高中必修4",
            description: "北师大版高中必修4",
            url: "/dicts/BeiShiGaoZhong_4_T.json",
            length: 336,
          },
          {
            id: "beishi5",
            label: "高中必修5",
            description: "北师大版高中必修5",
            url: "/dicts/BeiShiGaoZhong_5_T.json",
            length: 327,
          },
          {
            id: "beishi6",
            label: "高中选修6",
            description: "北师大版高中选修6",
            url: "/dicts/BeiShiGaoZhong_6_T.json",
            length: 271,
          },
          {
            id: "beishi7",
            label: "高中选修7",
            description: "北师大版高中选修7",
            url: "/dicts/BeiShiGaoZhong_7_T.json",
            length: 334,
          },
          {
            id: "beishi8",
            label: "高中选修8",
            description: "北师大版高中选修8",
            url: "/dicts/BeiShiGaoZhong_8_T.json",
            length: 364,
          },
          {
            id: "beishi9",
            label: "高中选修9",
            description: "北师大版高中选修9",
            url: "/dicts/BeiShiGaoZhong_9_T.json",
            length: 299,
          },
          {
            id: "beishi10",
            label: "高中选修10",
            description: "北师大版高中选修10",
            url: "/dicts/BeiShiGaoZhong_10_T.json",
            length: 267,
          },
          {
            id: "beishi11",
            label: "高中选修11",
            description: "北师大版高中选修11",
            url: "/dicts/BeiShiGaoZhong_11_T.json",
            length: 330,
          },
        ],
      },
      {
        label: "冀教版",
        children: [
          {
            id: "jijiao1",
            label: "冀教 3 上",
            description: "冀教版三年级起点三年级上",
            url: "/dicts/jiJiao3-1.json",
            length: 75,
          },
          {
            id: "jijiao2",
            label: "冀教 3 下",
            description: "冀教版三年级起点三年级下",
            url: "/dicts/jiJiao3-2.json",
            length: 76,
          },
          {
            id: "jijiao3",
            label: "冀教 4 上",
            description: "冀教版三年级起点四年级上",
            url: "/dicts/jiJiao4-1.json",
            length: 78,
          },
          {
            id: "jijiao4",
            label: "冀教 4 下",
            description: "冀教版三年级起点四年级下",
            url: "/dicts/jiJiao4-2.json",
            length: 84,
          },
          {
            id: "jijiao5",
            label: "冀教 5 上",
            description: "冀教版三年级起点五年级上",
            url: "/dicts/jiJiao5-1.json",
            length: 79,
          },
          {
            id: "jijiao6",
            label: "冀教 5 下",
            description: "冀教版三年级起点五年级下",
            url: "/dicts/jiJiao5-2.json",
            length: 96,
          },
          {
            id: "jijiao7",
            label: "冀教 6 上",
            description: "冀教版三年级起点六年级上",
            url: "/dicts/jiJiao6-1.json",
            length: 66,
          },
          {
            id: "jijiao8",
            label: "冀教 6 下",
            description: "冀教版三年级起点六年级下",
            url: "/dicts/jiJiao6-2.json",
            length: 51,
          },
          {
            id: "jijiao9",
            label: "冀教 7 上",
            description: "冀教版三年级起点七年级上",
            url: "/dicts/jiJiao7-1.json",
            length: 561,
          },
          {
            id: "jijiao10",
            label: "冀教 7 下",
            description: "冀教版三年级起点七年级下",
            url: "/dicts/jiJiao7-2.json",
            length: 514,
          },
          {
            id: "jijiao11",
            label: "冀教 8 上",
            description: "冀教版三年级起点八年级上",
            url: "/dicts/jiJiao8-1.json",
            length: 420,
          },
          {
            id: "jijiao12",
            label: "冀教 8 下",
            description: "冀教版三年级起点八年级下",
            url: "/dicts/jiJiao8-2.json",
            length: 487,
          },
          {
            id: "jijiao13",
            label: "冀教 9 上",
            description: "冀教版三年级起点九年级全册",
            url: "/dicts/jiJiao9.json",
            length: 636,
          },
        ],
      },
      {
        label: "其他",
        children: [
          {
            id: "BJJuniorHigh",
            label: "北京初中",
            description: "北京初中",
            url: "/dicts/beijing_junior_high_school.json",
            length: 1844,
          },
          {
            id: "ReadingExplorer3",
            label: "Reading Explorer 3",
            description: "词汇表来自Reading Explorer 3, Third Edition",
            url: "/dicts/ReadingExplorer3.json",
            length: 239,
          },
          {
            id: "Cambridge_JOIN_IN",
            label: "剑桥小学英语 JOIN IN",
            description:
              "外研社和剑桥大学出版社依据《义务教育英语课程标准》要求联合为我国小学生开发的一套英语教材。",
            url: "/dicts/Cambridge_JOIN_IN.json",
            length: 1350,
          },
        ],
      },
    ],
  },
];

// 递归扁平化词典树，只提取有 id 的词典项
function flattenDictTree(tree: any[]): any[] {
  const result: any[] = []
  
  tree.forEach(item => {
    if (item.children && item.children.length > 0) {
      // 如果有子节点，递归处理
      result.push(...flattenDictTree(item.children))
    } else if (item.id) {
      // 如果没有子节点且有 id，说明是词典项
      result.push(item)
    }
  })
  
  return result
}

// 导出拍平后的词典数组
export const flatDictList = flattenDictTree(dictTree)
